### PR TITLE
Zero --> Null for missing values

### PR DESCRIPTION
**Pull request by cernst1980**
For flot charts, null values would be better than zero values.
In flot, it can be configured if null values should be null, ignored or zero.

bildschirmfoto 2018-01-25 um 00 08 59

### CODE REVIEW

**Comment by NemoN** [comment]
+1

**Comment by Pix---** [comment]
If you do not tag the option "Werte vor jeder Aktualisierung nullen" in the adapter settings the last known value will be kept and the flot chart won't be disrupted.

If you insist on having always up to date values you have to tag the option. Then - in case of an error while receiving new data from tankerkoenig or in case the station is closed - the new value is 0. 

Optin:
See 0 ----> Price is not up to date or station is closed
See other value ----> price is up to date*

Optout:
see last value (possibly not up to date)
chart ist fluent, because no null or 0 ist written.


*up to date means the last known value on tankerkoenig.

**Comment by cernst1980** [comment]
1. I do not want last known but actual, valid and up-to-date value or no value at all (null)
2. I accept gaps in flot charts when stations are closed or in case of any errors
3. 0 is theoretically a valid value (free fuel), null means no value (error or station closed)
4. I don´t want zero values, because fuel is not free when station is closed and the jumps (vertical lines) in flot chart are bad
5. In flot, it can be configured if null values should be null, ignored or zero

This can´t be achieved with the option "Werte vor jeder Aktualisierung nullen", neither optin nor optout will work.
So my suggestion would be to use null instead of zero...

Do you see any disadvantages of using null?

**Comment by cernst1980** [comment]
At least, feed would be fine as this value is primarly used for flot (in my case).
short and 3rd are connected, so either both or none should be changed imho.
For name, the best would be to never reset the value, only overwrite it with new values.

So changing only feed would be fine (for me) for now.

**Pull request closed without merging**
